apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
  namespace: default
spec:
  containers:
    - name: test-echoserver
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 8080