apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-data-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-data
  template:
    metadata:
      labels:
        app: shared-data
    spec:
      volumes:
        - name: p-volume
          persistentVolumeClaim:
            claimName: p-claim
      containers:
        - name: busybox
          image: busybox:latest
          command:
            - /bin/sh
            - -c
            - >
              while true;
              do echo "$(date) - busybox записал в общий файл случайное число $RANDOM" >> /out/file;
              sleep 5;
              done;
          volumeMounts:
            - name: p-volume
              mountPath: /out
        - name: multitool
          image: wbitt/network-multitool:latest
          command:
            - /bin/sh
            - -c
            - >
              while true;
              do cat /in/file;
              echo "multitool прочитал общий файл";
              sleep 5;
              done;
          volumeMounts:
            - name: p-volume
              mountPath: /in