apiVersion: v1
kind: PersistentVolume
metadata:
  name: p-volume
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/pv-data01"