apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-nodeport-svc
spec:
  selector:
    app: nginx-multitool
  type: NodePort
  ports:
    - name: nginx-port
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
    - name: multitool-port
      port: 8080
      targetPort: 8080
      nodePort: 30081
      protocol: TCP